In [1]:
import numpy as np

In [2]:
x = np.array([[0, 0, 1],
             [0, 1, 1],
             [1, 0, 1],
             [1, 1, 1]])

y = np.array([[0], [1], [1], [0]])

In [23]:
print(x)
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [5]:
# Model definition

num_epochs = 100000


# 5 neurons in the hidden layer
syn0 = 2 * np.random.random((3, 5)) - 1
syn1 = 2 * np.random.random((5, 1)) - 1

In [21]:
print(syn0)

[[-0.86697401  0.74500188 -0.53588549  0.84822396 -0.63203471]
 [ 0.6706884  -0.43962233  0.77255021  0.71362277 -0.35390137]
 [ 0.11254249 -0.2024186   0.46936584  0.79775742  0.29747511]]


In [22]:
print(syn1)

[[-0.49106019]
 [ 0.41245528]
 [-0.72566368]
 [ 0.80987308]
 [-0.8901051 ]]


In [24]:
def sigmoid(x, deriv = False):
    if deriv:
        return x * (1 - x)
        
    x = 1 / (1 + np.exp(-x))

    return x

In [25]:
sigmoid(5)
sigmoid(5, deriv=True)

-20

In [ ]:
# Train Function
def train(x, y, syn0, syn1, num_epochs):
    for epoch in num_epochs:
        l0 = x
        l1 = sigmoid(np.dot(l0, syn0))
        l2 = sigmoid(np.dot(l1, syn1))
        
        #  Error at the output layer
        l2_error = y - l2
        
        # Derivative of the error for Gradient Descent
        l2_derivative = l2_error * sigmoid(l2, deriv=True)
        
        # Contribution of l2 to l1
        l1_error = l2_derivative.dot(syn1.T)
        
        if j % 1000 == 0:
            print(" The training error is {0} and the accuracy is {1}".format(np.mean(abs())))
        
        # Derivative for gradient descent 
        l1_derivative = l1_error * sigmoid(l1, deriv=True)
        
        # Update the weights 
        syn1 += np.dot(l1.T, l2_derivative)
        syn0 += np.dot(l0.T, l1_derivative)
        
        