In [1]:
import numpy as np

In [2]:
x = np.array([[0, 0, 1],
             [0, 1, 1],
             [1, 0, 1],
             [1, 1, 1]])

y = np.array([[0], [1], [1], [0]])

In [3]:
print(x)
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [4]:
# Model definition

num_epochs = 100000


# 5 neurons in the hidden layer
syn0 = 2 * np.random.random((3, 5)) - 1
syn1 = 2 * np.random.random((5, 1)) - 1

In [5]:
print(syn0)

[[-0.80554907 -0.48184687 -0.16124009 -0.79601376  0.93315435]
 [ 0.60482338  0.40575121  0.50729765 -0.35305451  0.22876282]
 [-0.46908305  0.56796475 -0.96940412 -0.92742003  0.01117627]]


In [6]:
print(syn1)

[[ 0.01719185]
 [-0.45442365]
 [-0.79347534]
 [-0.39750967]
 [ 0.03009025]]


In [7]:
def sigmoid(x, deriv = False):
    if deriv:
        return x * (1 - x)
        
    x = 1 / (1 + np.exp(-x))

    return x

In [8]:
sigmoid(5)
sigmoid(5, deriv=True)

-20

In [19]:
# Train Function
def train(x, y, syn0, syn1, num_epochs):
    for epoch in range(num_epochs):
        l0 = x
        l1 = sigmoid(np.dot(l0, syn0))
        l2 = sigmoid(np.dot(l1, syn1))
        
        #  Error at the output layer
        l2_error = y - l2
        
        # Derivative of the error for Gradient Descent
        l2_derivative = l2_error * sigmoid(l2, deriv=True)
        
        # Contribution of l2 to l1
        l1_error = l2_derivative.dot(syn1.T)
        
        if epoch % 1000 == 0:
            print(" Training .....  \t Error : {0}".format(np.mean(abs(l2_error))))
        
        # Derivative for gradient descent 
        l1_derivative = l1_error * sigmoid(l1, deriv=True)
        
        # Update the weights 
        syn1 += np.dot(l1.T, l2_derivative)
        syn0 += np.dot(l0.T, l1_derivative)
    print("Error: {0}".format(l2_error))

In [20]:
train(x, y, syn0, syn1, num_epochs)

 The training error is 0.00119975272603
 The training error is 0.00119818947655
 The training error is 0.00119663218456
 The training error is 0.00119508081255
 The training error is 0.00119353532334
 The training error is 0.00119199568008
 The training error is 0.00119046184621
 The training error is 0.00118893378553
 The training error is 0.00118741146214


 The training error is 0.00118589484043
 The training error is 0.00118438388512
 The training error is 0.00118287856124
 The training error is 0.00118137883409
 The training error is 0.0011798846693
 The training error is 0.00117839603278
 The training error is 0.00117691289073
 The training error is 0.00117543520964
 The training error is 0.00117396295627
 The training error is 0.0011724960977


 The training error is 0.00117103460125
 The training error is 0.00116957843452
 The training error is 0.00116812756541
 The training error is 0.00116668196206
 The training error is 0.00116524159289
 The training error is 0.00116380642659
 The training error is 0.00116237643209
 The training error is 0.00116095157859
 The training error is 0.00115953183556
 The training error is 0.0011581171727
 The training error is 0.00115670755997


 The training error is 0.00115530296758
 The training error is 0.00115390336597
 The training error is 0.00115250872584
 The training error is 0.00115111901813
 The training error is 0.001149734214
 The training error is 0.00114835428486
 The training error is 0.00114697920234
 The training error is 0.00114560893832
 The training error is 0.00114424346488
 The training error is 0.00114288275435
 The training error is 0.00114152677926


 The training error is 0.00114017551239
 The training error is 0.0011388289267
 The training error is 0.00113748699541
 The training error is 0.00113614969191
 The training error is 0.00113481698983
 The training error is 0.00113348886301
 The training error is 0.00113216528547
 The training error is 0.00113084623147
 The training error is 0.00112953167545
 The training error is 0.00112822159206
 The training error is 0.00112691595614


 The training error is 0.00112561474274
 The training error is 0.0011243179271
 The training error is 0.00112302548466
 The training error is 0.00112173739102
 The training error is 0.00112045362202
 The training error is 0.00111917415363
 The training error is 0.00111789896207
 The training error is 0.00111662802368
 The training error is 0.00111536131502
 The training error is 0.00111409881283


 The training error is 0.00111284049401
 The training error is 0.00111158633565
 The training error is 0.001110336315
 The training error is 0.00110909040951
 The training error is 0.00110784859678
 The training error is 0.00110661085458
 The training error is 0.00110537716086
 The training error is 0.00110414749372
 The training error is 0.00110292183144


 The training error is 0.00110170015246
 The training error is 0.00110048243538
 The training error is 0.00109926865896
 The training error is 0.00109805880211
 The training error is 0.00109685284391
 The training error is 0.00109565076359
 The training error is 0.00109445254055
 The training error is 0.0010932581543
 The training error is 0.00109206758455
 The training error is 0.00109088081113
 The training error is 0.00108969781403


 The training error is 0.00108851857339
 The training error is 0.00108734306947
 The training error is 0.00108617128272
 The training error is 0.00108500319368
 The training error is 0.00108383878308
 The training error is 0.00108267803177
 The training error is 0.00108152092071
 The training error is 0.00108036743106
 The training error is 0.00107921754405
 The training error is 0.0010780712411
 The training error is 0.00107692850373


 The training error is 0.0010757893136
 The training error is 0.00107465365251
 The training error is 0.00107352150238
 The training error is 0.00107239284527
 The training error is 0.00107126766335
 The training error is 0.00107014593894
 The training error is 0.00106902765447
