In [27]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.array([[0, 0, 1],
             [0, 1, 1],
             [1, 0, 1],
             [1, 1, 1]])

y = np.array([[0], [1], [1], [0]])

In [3]:
print(x)
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [93]:
# Model definition

num_epochs = 100000


# 5 neurons in the hidden layer
syn0 = 2 * np.random.random((3, 5)) - 1
syn1 = 2 * np.random.random((5, 1)) - 1

In [5]:
print(syn0)

[[-0.80554907 -0.48184687 -0.16124009 -0.79601376  0.93315435]
 [ 0.60482338  0.40575121  0.50729765 -0.35305451  0.22876282]
 [-0.46908305  0.56796475 -0.96940412 -0.92742003  0.01117627]]


In [6]:
print(syn1)

[[ 0.01719185]
 [-0.45442365]
 [-0.79347534]
 [-0.39750967]
 [ 0.03009025]]


In [ ]:
# Sigmoid function to bound values between 0 and 1 at the output of each neuron
def sigmoid(x, deriv = False):
    if deriv:
        return x * (1 - x)
        
    x = 1 / (1 + np.exp(-x))

    return x

x_axis = range(-100, 100)
y_axis = []
for value in x_axis:
    y = sigmoid(value)
    y_axis.append(y)

plt.plot(x_axis, y_axis)
plt.show()

In [84]:
# Train Function
def train(x, y, syn0, syn1, num_epochs):
    accumulated_errors = []
    for epoch in range(num_epochs):
        l0 = x
        l1 = sigmoid(np.dot(l0, syn0))
        l2 = sigmoid(np.dot(l1, syn1))
        
        #  Error at the output layer
        l2_error = y - l2
        
        # Derivative of the error for Gradient Descent
        l2_derivative = l2_error * sigmoid(l2, deriv=True)
        
        # Contribution of l2 to l1
        l1_error = l2_derivative.dot(syn1.T)
        
        training_error = np.mean(abs(l2_error))
        accumulated_errors.append(training_error)
        
        if epoch % 1000 == 0:
            print(" Training .....  \t Error : {0}".format(training_error))
        
        # Derivative for gradient descent 
        l1_derivative = l1_error * sigmoid(l1, deriv=True)
        
        # Update the weights 
        syn1 += np.dot(l1.T, l2_derivative)
        syn0 += np.dot(l0.T, l1_derivative)
    print("Error: {0}".format(training_error))
    return accumulated_errors

In [94]:
errors = train(x, y, syn0, syn1, num_epochs)

 Training .....  	 Error : 0.499213393222
 Training .....  	 Error : 0.0409120728628
 Training .....  	 Error : 0.0235376250169


 Training .....  	 Error : 0.0178524844778
 Training .....  	 Error : 0.0148506636039
 Training .....  	 Error : 0.0129395174756
 Training .....  	 Error : 0.0115924885053
 Training .....  	 Error : 0.0105801042674
 Training .....  	 Error : 0.00978477597669
 Training .....  	 Error : 0.00913938669199


 Training .....  	 Error : 0.00860254633015
 Training .....  	 Error : 0.00814719608001
 Training .....  	 Error : 0.00775481956778
 Training .....  	 Error : 0.0074122717709
 Training .....  	 Error : 0.00710993455011
 Training .....  	 Error : 0.00684059004173
 Training .....  	 Error : 0.00659870394821


 Training .....  	 Error : 0.00637995363347
 Training .....  	 Error : 0.00618090810722
 Training .....  	 Error : 0.00599880539121
 Training .....  	 Error : 0.00583139412791
 Training .....  	 Error : 0.00567681864483
 Training .....  	 Error : 0.00553353407249
 Training .....  	 Error : 0.00540024266287
 Training .....  	 Error : 0.0052758453306


 Training .....  	 Error : 0.00515940430126
 Training .....  	 Error : 0.0050501139826
 Training .....  	 Error : 0.00494727800436
 Training .....  	 Error : 0.00485029094231
 Training .....  	 Error : 0.00475862363889
 Training .....  	 Error : 0.00467181131411


 Training .....  	 Error : 0.00458944386157
 Training .....  	 Error : 0.00451115787104
 Training .....  	 Error : 0.00443663002634
 Training .....  	 Error : 0.00436557160733
 Training .....  	 Error : 0.0042977238843
 Training .....  	 Error : 0.00423285423894
 Training .....  	 Error : 0.00417075288026


 Training .....  	 Error : 0.00411123005062
 Training .....  	 Error : 0.00405411363804
 Training .....  	 Error : 0.00399924712663
 Training .....  	 Error : 0.00394648783015
 Training .....  	 Error : 0.00389570536371
 Training .....  	 Error : 0.00384678031657
 Training .....  	 Error : 0.00379960309546
 Training .....  	 Error : 0.00375407291338


 Training .....  	 Error : 0.0037100969025
 Training .....  	 Error : 0.00366758933377
 Training .....  	 Error : 0.00362647092831
 Training .....  	 Error : 0.00358666824818
 Training .....  	 Error : 0.00354811315588
 Training .....  	 Error : 0.00351074233362


 Training .....  	 Error : 0.00347449685481
 Training .....  	 Error : 0.0034393218011
 Training .....  	 Error : 0.00340516591932
 Training .....  	 Error : 0.00337198131373
 Training .....  	 Error : 0.00333972316905
 Training .....  	 Error : 0.00330834950104
 Training .....  	 Error : 0.0032778209311
 Training .....  	 Error : 0.00324810048257


 Training .....  	 Error : 0.00321915339598
 Training .....  	 Error : 0.00319094696143
 Training .....  	 Error : 0.00316345036618
 Training .....  	 Error : 0.00313663455578
 Training .....  	 Error : 0.00311047210747
 Training .....  	 Error : 0.00308493711448
 Training .....  	 Error : 0.00306000508025
 Training .....  	 Error : 0.00303565282143


 Training .....  	 Error : 0.00301185837897
 Training .....  	 Error : 0.00298860093642
 Training .....  	 Error : 0.00296586074479
 Training .....  	 Error : 0.00294361905335
 Training .....  	 Error : 0.00292185804581
 Training .....  	 Error : 0.00290056078145
 Training .....  	 Error : 0.00287971114067
 Training .....  	 Error : 0.00285929377466


 Training .....  	 Error : 0.00283929405872
 Training .....  	 Error : 0.00281969804908
 Training .....  	 Error : 0.00280049244269
 Training .....  	 Error : 0.00278166454001
 Training .....  	 Error : 0.00276320221031
 Training .....  	 Error : 0.00274509385939
 Training .....  	 Error : 0.00272732839955


 Training .....  	 Error : 0.00270989522151
 Training .....  	 Error : 0.0026927841683
 Training .....  	 Error : 0.00267598551079
 Training .....  	 Error : 0.00265948992486
 Training .....  	 Error : 0.00264328847002
 Training .....  	 Error : 0.00262737256939
 Training .....  	 Error : 0.00261173399094
 Training .....  	 Error : 0.00259636482995


 Training .....  	 Error : 0.00258125749245
 Training .....  	 Error : 0.00256640467973
 Training .....  	 Error : 0.00255179937382
 Training .....  	 Error : 0.00253743482371
 Training .....  	 Error : 0.00252330453255
 Training .....  	 Error : 0.00250940224542
 Training .....  	 Error : 0.00249572193797
 Training .....  	 Error : 0.00248225780555


 Training .....  	 Error : 0.00246900425313
Error: 0.00245596883323


In [95]:
def plot_learning_curve(errors, num_epochs):
    plt.plot(range(num_epochs), errors)
    plt.xlabel(' Number of Iterations')
    plt.ylabel( ' Training error')
    plt.title(' Training Curve')
    plt.show()

In [96]:
plot_learning_curve(errors, num_epochs)

ValueError: x and y must not be None